language: ruby

env:
  - TEST_CXX=1 TEST_NODE=1
  - TEST_CXX=1 SUDO=1
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.8.7-p374 TEST_RUBYGEMS_VERSION=1.8.25
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.9.3 TEST_USH=1
  - TEST_NGINX=1 TEST_STANDALONE=1
  - TEST_APACHE2=1
  - TEST_SOURCE_PACKAGING=1

before_install:
  - 'gem uninstall bundler bundle rubygems-update --all -x && gem update --system 2.6.1 && gem install bundler --version 1.11.2 && gem uninstall rubygems-update --all -x && gem update --system 2.6.4 && gem remove bundler && gem install bundler --version 1.11.2'
  - 'gem --version'
  - 'bundle --version'
install: "true"
script: ./dev/ci/run_travis.sh

cache:
  directories:
    - cache

notifications:
  slack: phusionnl:PH5p7JYXyv2XLDpICHh8Nj6F
