language: ruby

env:
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.9.3 TEST_USH=1

before_install:
  - 'gem uninstall bundler bundle rubygems-update --all -x && gem update --system 2.6.1 && gem install bundler && gem uninstall rubygems-update --all -x && gem update --system 2.6.4'
  - 'gem --version'
  - 'bundle --version'
install: "true"
script: ./dev/ci/run_travis.sh

cache:
  directories:
    - cache

notifications:
  slack: phusionnl:PH5p7JYXyv2XLDpICHh8Nj6F
